server:
  port: 8080

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: user-ms
          uri: lb://user-ms
          predicates:
            - Path=/user/**
        - id: movies-ms
          uri: lb://movies-ms
          predicates:
            - Path=/movies/**
        - id: bookings-ms
          uri: lb://bookings-ms
          predicates:
            - Path=/bookings/**
        - id: reviews-ms
          uri: lb://reviews-ms
          predicates:
            - Path=/reviews/**


eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



